# Använd en basbild med Python
FROM python:3.11.5

# Ställ in arbetskatalogen i containern
WORKDIR /app

# Kopiera main.py till containern
COPY src/main.py .

# Ange det kommando som ska köras när containern startar
CMD ["python", "main.py"]
